--DB: utente ; user: utente ; pass: utente ;

CREATE TABLE postType (
    posttype_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    posttype_name VARCHAR(32)
);

CREATE TABLE utenti (
    utente_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(256) UNIQUE,
    cognome VARCHAR(256),
    password VARCHAR(256) NOT NULL,
    urlFotoProfilo VARCHAR(256)
);

CREATE TABLE posts (
    post_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(1024),
    type INTEGER,
    FOREIGN KEY (type) REFERENCES postType(postType_id),
    author INTEGER,
    FOREIGN KEY (author) REFERENCES utenti(utente_id)
);

CREATE TABLE hearts (
   follower INTEGER,
   FOREIGN KEY (follower) REFERENCES utenti(utente_id),
   followed INTEGER,
   FOREIGN KEY (followed) REFERENCES utenti(utente_id),
   PRIMARY KEY (follower, followed)
);


ALTER TABLE utenti ADD email VARCHAR(256);


INSERT INTO utenti (utente_id, name, email, cognome, password, urlfotoprofilo)
VALUES (default,
        'ale',
        'moneysniper@gmail.com',
        'Satta',
        '123',
        'img/fotoprof.jpg');

INSERT INTO utenti (utente_id, name, email, cognome, password, urlfotoprofilo)
VALUES (default,
        'allen',
        'gang@gmail.com',
        'iverson',
        '123',
        'img/user1.gif');

INSERT INTO utenti (utente_id, name, email, cognome, password, urlfotoprofilo)
VALUES (default,
        'shawn',
        'gang7@gmail.com',
        'carter',
        '123',
        'img/user2.jpg');


--Popolamento tabella PostType
INSERT INTO posttype (posttype_id, posttype_name)
VALUES (default, 'TEXT');

INSERT INTO posttype (posttype_id, posttype_name)
VALUES (default, 'IMAGE');

--Popolamento tabella Post
INSERT INTO posts (post_id, content, type, author)
VALUES (default,
        'festa',
        1,
        1);

INSERT INTO posts (post_id, content, type, author)
VALUES (default,
        'img/juventuslogo.png',
        2,
        1);

INSERT INTO posts (post_id, content, type, author)
VALUES (default,
        'img/juventuslogo.png',
        2,
        1);

INSERT INTO posts (post_id, content, type, author)
VALUES (default,
        'Fino alla fine',
        1,
        2);


--Popolamento tabella Hearts (relativa alle amicizie)
INSERT INTO hearts (follower, followed)
VALUES (1, 2),
       (1, 3),
       (1, 4),
       (2, 1),
       (2, 4);

INSERT INTO hearts (follower, followed)
VALUES (3, 1),
       (3, 2);

INSERT INTO hearts (follower, followed)
VALUES (4, 2);

